<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>新增至購物清單</description>
   <name>button_addcart</name>
   <tag></tag>
   <elementGuidId>6b920e2a-6294-4cdc-9f43-15879d8047d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btnAddToCart-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
