<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>前往付款</description>
   <name>button_pay</name>
   <tag></tag>
   <elementGuidId>93e1de10-74e3-4c23-9f6d-93f6b14b2725</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.v-card__actions:nth-child(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
