<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Email</description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>43050c63-8fd2-4a84-bf6e-2607a57c70ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#receipt__personal-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
